packages:
 - docs
 - packages/*

onlyBuiltDependencies:
 - bcrypt

catalogs:
 # Can be referenced through "catalog:kitql"
 kitql:
  '@kitql/helpers': 0.8.11
  '@kitql/eslint-config': 0.5.8
  '@kitql/handles': 0.2.3
  '@kitql/internals': 0.9.9

 testing:
  '@playwright/test': 1.50.0

 lib-author-helper:
  '@changesets/changelog-github': 0.5.0
  '@changesets/cli': 2.27.1

catalog:
 '@clack/prompts': 0.7.0
 '@iconify-json/fxemoji': 1.2.0
 '@iconify-json/heroicons': 1.2.0
 '@mdi/js': 7.4.47
 '@melt-ui/svelte': 0.86.3
 '@oslojs/crypto': 1.0.1
 '@oslojs/encoding': 1.1.0
 '@oslojs/otp': 1.1.0
 '@sveltejs/adapter-node': 5.2.2
 '@sveltejs/adapter-static': 3.0.4
 '@sveltejs/kit': 2.7.3
 '@sveltejs/package': 2.3.2
 '@sveltejs/vite-plugin-svelte': 3.1.2
 '@sveltepress/theme-default': 5.0.6
 '@sveltepress/vite': 1.1.3
 '@types/nodemailer': 6.4.14
 arctic: 3.5.0
 autoprefixer: 10.4.19
 bcryptjs: 3.0.2
 clsx: 2.1.1
 cron: 3.1.7
 daisyui: 4.12.14
 esm-env: 1.0.0
 nodemailer: 6.9.14
 postcss: 8.4.38
 prettier: 3.4.2
 svelte: 4.2.18
 svelte-check: 4.0.5
 svelty-email: 0.0.11
 tailwind-merge: 2.3.0
 tailwindcss: 3.4.4
 tslib: 2.8.0
 typescript: 5.5.4
 vite: 5.4.1
 vite-plugin-kit-routes: 0.8.3
 vite-plugin-stripper: 0.5.4
 vitest: 3.0.1
