packages:
 - docs
 - packages/*

patchedDependencies:
 '@melt-ui/svelte@0.86.3': patches/@melt-ui__svelte@0.86.3.patch

catalogs:
 docs:
  '@astrojs/starlight': 0.34.3
  accessible-astro-components: 4.1.0
  astro: 5.11.0
  astro-icon: 1.1.5
  sharp: 0.34.1
  prettier-plugin-astro: 0.14.1

 tooling:
  typescript: 5.8.2
  vite: 6.3.5
  '@tsconfig/svelte': 5.0.2
  tslib: 2.8.0
  vite-plugin-watch-and-run: 1.7.5
  vite-plugin-kit-routes: 1.0.2
  vite-plugin-stripper: 0.9.2
  esm-env: 1.2.2
  '@clack/prompts': 0.11.0
  prettier: 3.6.2

 kitql:
  '@kitql/helpers': 0.8.13
  '@kitql/eslint-config': 0.7.2
  '@kitql/internals': 0.10.5

 testing:
  '@playwright/test': 1.54.1
  vitest: 3.2.3

 lib-author-helper:
  '@changesets/changelog-github': 0.5.0
  '@changesets/cli': 2.29.4

 svelte:
  'svelte': 5.34.3
  svelte-check: 4.2.1
  svelte-micro: 2.5.7

 sveltekit:
  '@sveltejs/adapter-node': 5.2.2
  '@sveltejs/kit': 2.25.1
  '@sveltejs/vite-plugin-svelte': 5.1.0
  '@sveltejs/package': 2.3.2

 ui:
  mermaid: 11.8.0
  '@mdi/js': 7.4.47
  '@melt-ui/svelte': 0.86.3
  autoprefixer: 10.4.19
  postcss: 8.5.3
  tailwindcss: 3.4.4
  tailwind-merge: 2.6.0
  clsx: 2.1.1
  daisyui: 4.12.14

 prod:
  '@oslojs/crypto': 1.0.1
  '@oslojs/encoding': 1.1.0
  '@oslojs/otp': 1.1.0
  '@types/nodemailer': 6.4.17
  nodemailer: 7.0.4
  arctic: 3.7.0
  bcryptjs: 3.0.2
  cron: 4.3.0
  '@layerstack/utils': 1.0.0
  '@layerstack/svelte-actions': 1.0.0
  mjml: 4.15.3
  sailkit: 0.3.0
