packages:
 - docs
 - packages/*

catalogs:
 docs:
  '@astrojs/starlight': 0.36.0
  accessible-astro-components: 5.0.1
  astro: 5.15.5
  astro-icon: 1.1.5
  sharp: 0.34.1
  prettier-plugin-astro: 0.14.1

 tooling:
  typescript: 5.9.3
  vite: 7.1.10
  '@tsconfig/svelte': 5.0.2
  tslib: 2.8.0
  vite-plugin-watch-and-run: 1.7.5
  vite-plugin-kit-routes: 1.0.2
  vite-plugin-stripper: 0.9.2
  esm-env: 1.2.2
  '@clack/prompts': 0.11.0
  prettier: 3.6.2

 kitql:
  '@kitql/helpers': 0.8.13
  '@kitql/eslint-config': 0.8.0-next.4
  '@kitql/internals': 0.10.5

 testing:
  '@playwright/test': 1.56.0
  vitest: 3.2.3

 lib-author-helper:
  '@changesets/changelog-github': 0.5.0
  '@changesets/cli': 2.29.4

 svelte:
  'svelte': 5.40.0
  svelte-check: 4.3.0
  svelte-micro: 2.5.7

 sveltekit:
  '@sveltejs/adapter-node': 5.3.2
  '@sveltejs/kit': 2.46.5
  '@sveltejs/vite-plugin-svelte': 6.2.1
  '@sveltejs/package': 2.5.4

 ui:
  mermaid: 11.12.0
  '@mdi/js': 7.4.47
  '@melt-ui/svelte': 0.86.6
  tailwindcss: 4.1.14
  '@tailwindcss/vite': 4.1.14
  tailwind-merge: 2.6.0
  clsx: 2.1.1
  daisyui: 5.5.0

 prod:
  '@oslojs/crypto': 1.0.1
  '@oslojs/encoding': 1.1.0
  '@oslojs/otp': 1.1.0
  '@types/nodemailer': 7.0.2
  nodemailer: 7.0.4
  arctic: 3.7.0
  bcryptjs: 3.0.2
  cron: 4.3.0
  '@layerstack/utils': 1.0.0
  '@layerstack/svelte-actions': 1.0.0
