packages:
  - docs
  - packages/*

onlyBuiltDependencies:
  - bcrypt

catalogs:
  # Can be referenced through "catalog:kitql"
  kitql:
    '@kitql/helpers': 0.8.12
    '@kitql/eslint-config': 0.5.4
    '@kitql/handles': 0.2.3
    '@kitql/internals': 0.10.1
