services:
 - type: web
   name: firstly-static
   env: static
   repo: https://github.com/jycouet/firstly
   branch: main
   buildCommand: npm i -g pnpm; pnpm install --production=false; pnpm -F docs build
   staticPublishPath: ./docs/dist
   buildFilter:
    paths:
     - docs/**
   envVars:
    - key: NODE_VERSION
      value: 22.11.0
   #   - key: TZ
   #     value: utc
